version: '3.7'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=hiperion
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  donlod:
    image: angelopedroso/donlod-hiperion:1.0
    ports:
      - '9000:9000'
