const domains = [
  'it.pinterest.com',
  'pin.it',
  'br.pinterest.com',
  'pinterest.pt',
  'pinterest.br',
  'tiktok.com',
  'vm.tiktok.com',
  'm.tiktok.com',
  'instagram.com',
  'facebook.com',
  'mbasic.facebook.com',
  'm.facebook.com',
  'm.facebook.me',
  'fb.com',
  'twitter.com',
  't.twitter.com',
  't.co',
  'twitter.co',
  'chat.whatsapp.com',
  'wa.me',
  'youtube.com',
  'youtu.be',
  'reddit.com',
  'soundcloud.com',
]

export { domains }
